version: '3.0'
services:
  mongo:
    image: mongo
    restart: always
    expose:
      - "27017"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - MONGO_DB_ADDR=mongo
    ports:
      - "80:8000"
    links:
      - mongo