version: '3.0'
services:
  mongo:
    image: mongo
    restart: always
    expose:
      - "27017"
  web:
    build: .
    command: "./run.sh"
    environment:
      - MONGO_DB_ADDR=mongo
      - DEBUG=False
      - ENFORCE_SCHEMA=False
    ports:
      - "80:8000"
    links:
      - mongo