# Generated by Django 2.2.7 on 2019-11-21 18:25

import backend.main.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('topic', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('last_scanned', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', djongo.models.fields.EmbeddedModelField(model_container=backend.main.models.Job, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('hashtag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hashtag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeseries', djongo.models.fields.EmbeddedModelField(model_container=backend.main.models.DataPoint, null=True)),
                ('hashtag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hashtag')),
            ],
        ),
    ]
